### ISSUE TITLE
Condition not executed successfully!

### ISSUE THREAD

**Issue by abhishekpatel946** [abhishekpatel946/Slack-Clone#2]
### Javascript code not executed!
**There is a `src/components/Sidebar/SidebarOption.js` that ternary condition was not executed successfully**

```javascript
      // ternary condition will not executed in right way
      onClick={addChannelOption ? addChannel : selectChannel}
```

**Problem**
> all time if I keep selectChannel as a false or put in last so always run selectChannel only.

**Right Way to Execution**
> the condition is that if the user clicks on **Add Channel** then based upon the condition if the channel is already present then no need to add the **Channel**. Or else if **Channel** not in present then a prompt box will appear and write the channel name through the prompt box and code will further be executed

**Comment by Sylviaan** [comment]
I would like to work on this, could you assign it to me.

**Comment by abhishekpatel946** [comment]
Hey, @Mehrapi you're welcome go ahead!

**Comment by Sylviaan** [comment]
I was able to get the prompt box to appear, but it appear as well when the other items in the sidebar is clicked. I'm still trying to figure out how to fix this.

**Comment by abhishekpatel946** [comment]
> I was able to get the prompt box to appear, but it appear as well when the other items in the sidebar is clicked. I'm still trying to figure out how to fix this.

Yup! you're right actually when you clicked on the sidebar the event occurs.
You can fix it in this way.....

> When the user clicks on Add Channel then prompt box will appear. (Condition: `addChannel` ) will be executed

> And if the user clicks on any channel then go to the channel. (Condition: `selectChannel`) will be executed

**Comment by Sylviaan** [comment]
I'm stuck, I tried to add the condition, but the prompt still appear everywhere.

**Comment by abhishekpatel946** [comment]
> I'm stuck, I tried to add the condition, but the prompt still appear everywhere.

exactly that's the problem when I tested the project.

**Comment by Mehrapi** [comment]
The ternary condition is true for only one, AddChannel or Channell. That's why  the prompt appear everywhere.  How should I add  the condition and make it work?

**Comment by Mehrapi** [comment]
I didn't figure out how to make the condition work. I need help.

**Comment by Mehrapi** [comment]
This is my first time to deal with ternary condition.

**Comment by Sylviaan** [comment]
Now I understand, thanks.
